apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage
spec:
  containers:
    - image: nginx
      name: nginx
      volumeMounts:
          - mountPath: /scratch
            name: scratch-volume
          - mountPath: /app/data
            name: mealie-data
    - image: busybox
      name: busybox
      command: ["/bin/sh", "-c"]
      args: ["sleep 1000"]
      volumeMounts:
          - mountPath: /scratch
            name: scratch-volume
  volumes:
    - name: scratch-volume
      emptyDir:
        sizeLimit: 500Mi
    - name: mealie-data
      persistentVolumeClaim:
        claimName: mealie-data
